version: '3.6'

networks:
  default:
    external:
      name: monitoring

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:
  loki_data:

services:

  grafana:
    image: grafana/grafana:7.1.1
    volumes:
      - grafana_data:/var/lib/grafana
    command:  -config /etc/grafana/grafana.ini
    environment:
      - GF_SERVER_ROOT_URL=https://127.0.0.1:3000
    restart: always
    ports:
      - "127.0.0.1:3000:3000"

  loki:
    image: grafana/loki:1.6.1
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - loki_data:/loki
